feat: self supervised learning integration in sampler
jina-ai/finetuner pull request #336
Opened 2022-01-11 15:53 UTC by bwanglzu

2022-01-12 15:42 UTC, gmastrapas requested changes
Some comments

2022-01-12 15:42 UTC, gmastrapas commented on finetuner/tuner/augmentation.py
> +    target_channel_axis: int = 0,
update docstring as well

2022-01-12 15:42 UTC, gmastrapas commented on finetuner/tuner/pytorch/datasets.py
> +    def __getitem__(self, ind: int) -> Tuple['DocumentContentType', Tuple[int, int]]:
`Tuple['DocumentContentType', int]` ?

2022-01-12 15:47 UTC, gmastrapas commented
So basically if I pass unlabeled data (no tags nor matches) the ssl kicks in? What about custom `augment_fn`?

2022-01-12 15:49 UTC, tadejsv commented
@gmastrapas There is no `augment_fn`, you can use the `preprocess_fn` for that

2022-01-12 15:50 UTC, bwanglzu commented
i need to refactor `vision_preprocessor` a bit, hold on :)

2022-01-13 14:24 UTC, tadejsv approved these changes
Looks good

2022-01-13 14:41 UTC, gmastrapas approved these changes
LGTM!

2022-01-13 14:42 UTC, merged