crate the save_model dir automatically if it does not exists
jina-ai/finetuner pull request #429
Opened 2022-06-08 07:12 UTC by jerrychen1990

solve issue：https://github.com/jina-ai/finetuner/issues/427

2022-06-08 07:59 UTC, gmastrapas requested changes
Hey @jerrychen1990 ! Thanks for your contribution! Left a minor comment

2022-06-08 07:59 UTC, gmastrapas commented on finetuner/tuner/callback/best_model_checkpoint.py
> +            self._logger.info(f"{self._save_dir} not exists, will create one.")
Use single instead of double quotes

2022-06-08 12:51 UTC, gmastrapas commented
@jerrychen1990 you need to merge from main or rebase, and tests will probably be ok

2022-06-30 11:13 UTC, bwanglzu commented
I have backed up the OSS version, we'll close this PR since we'll not working on the current main anymore.

2022-06-30 11:13 UTC, closed without merging