feat: adopt hubble sdk on notebook login
jina-ai/finetuner pull request #576
Opened 2022-10-14 12:08 UTC by bwanglzu

---

- [ ] This PR references an open issue
- [ ] I have added a line about this change to CHANGELOG

2022-10-14 12:37 UTC, alexcg1 commented on finetuner/finetuner.py
> +        """Login to Hubble account, initialize a client object
```suggestion
        """Log in to Hubble account, initialize a client object
```

2022-10-14 12:37 UTC, alexcg1 commented on finetuner/finetuner.py
> +        :param force: If set to true, will overwrite token and re-login.
```suggestion
        :param force: If set to true, overwrite token and re-login.
```

2022-10-14 12:38 UTC, alexcg1 commented on finetuner/finetuner.py
> +        Note: This works for notebook, colab..
```suggestion
        Note: This works for Jupyter notebook, Google Colab..
```

2022-10-14 12:39 UTC, alexcg1 commented on docs/tasks/image-to-image.md
>  First you need to {ref}`login to Jina ecosystem <login-to-jina-ecosystem>`:
```suggestion
First, {ref}`log in to the Jina ecosystem <login-to-jina-ecosystem>`:
```

2022-10-14 12:41 UTC, alexcg1 commented on docs/get-started/how-it-works.md
> +Once you logged into the Jina Ecosystem with {meth}`~finetuner.login()` or `~finetuner.notebook_login()`,
```suggestion
Once you have logged in to the Jina Ecosystem with {meth}`~finetuner.login()` or `~finetuner.notebook_login()`, 
```

### Usage examples

- I will log in to foo
- I am logged in
- My login for foo is bar

God, I hate [grammar](https://english.stackexchange.com/questions/5302/log-in-to-or-log-into-or-login-to) :sweat_smile:

2022-10-14 12:41 UTC, alexcg1 commented on CHANGELOG.md
> +- Use latest hubble with `notebook_login` support ([#576](https://github.com/jina-ai/finetuner/pull/576))
```suggestion
- Use latest Hubble with `notebook_login` support ([#576](https://github.com/jina-ai/finetuner/pull/576))
```

2022-10-14 12:42 UTC, alexcg1 commented on README.md
> +finetuner.login()  # use finetuner.notebook_login() in jupyter notebook/google colab
```suggestion
finetuner.login()  # use finetuner.notebook_login() in Jupyter notebook/Google Colab
```

Can you change all occurrences?

2022-10-14 13:26 UTC, bwanglzu commented
@alexcg1 if you find this looks good please review again, otherwise will block us from merge

2022-10-14 13:51 UTC, alexcg1 requested changes

2022-10-14 13:51 UTC, alexcg1 commented on docs/walkthrough/integrate-with-jina.md
> +finetuner.login()  # use finetuner.notebook_login() in Jupyter notebook or Google colab()
Also, should be **C**olab, not **c**olab

2022-10-14 14:15 UTC, alexcg1 approved these changes
LGTM :+1:

2022-10-14 18:46 UTC, gmastrapas approved these changes

2022-10-16 12:58 UTC, bwanglzu commented
test failed blocked by : https://github.com/jina-ai/jina-hubble-sdk/pull/83

2022-10-16 15:44 UTC, gmastrapas requested changes

2022-10-16 15:44 UTC, gmastrapas commented on docs/tasks/text-to-image.md
> +finetuner.login()  # use finetuner.notebook_login() in Jupyter notebook or Google Colab
Can you update this tutorial with the correct da names? These are `fashion-train-data-clip` and `fashion-eval-data-clip`

2022-10-17 12:12 UTC, LMMilliken approved these changes

2022-10-17 12:14 UTC, guenthermi approved these changes
LGTM, only added one comment to be fixed.

2022-10-17 12:14 UTC, guenthermi commented on finetuner/finetuner.py
> +        :param force: If set to true, overwrite token and re-login.
Can you add the force parameter also to the login function. It also exists there.

2022-10-17 12:24 UTC, gmastrapas requested changes

2022-10-17 12:24 UTC, gmastrapas commented on docs/tasks/text-to-image.md
> +we already prepared the data, and we'll provide the names of training and evaluation data (`fashion-eval-train-clip` and `fashion-eval-data-clip`) directly to Finetuner.
the train data are `fashion-train-data-clip`. Update the snippet as well

2022-10-17 13:15 UTC, gmastrapas approved these changes

2022-10-17 13:20 UTC, merged