docs: update page on available models
jina-ai/finetuner pull request #725
Opened 2023-04-19 11:32 UTC by LMMilliken

This pr updates the section on choosing a model. The different tasks have been moved out of tabs and given their own headers to make it easier to reference them from notebooks or other pages.

---

- [ ] This PR references an open issue
- [ ] I have added a line about this change to CHANGELOG

2023-04-19 12:13 UTC, bwanglzu approved these changes
LGTM!

2023-04-19 12:27 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +Each of these models have their own variants and are designed to produce embeddings for a specific modality.
```suggestion
Each model has its own variants and is designed to produce embeddings for a specific modality.
```

2023-04-19 12:30 UTC, azayz approved these changes
LGTM

2023-04-19 12:30 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +To get a list of supported models during run-time, you can call:
```suggestion
To get a list of supported models at run-time, you can call:
```

2023-04-19 12:31 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +To get a list of supported models during run-time, you can call:
```suggestion
To get a list of supported models at run-time, you can call:
```

2023-04-19 12:33 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +CLIP models are used to text-to-image search tasks, and we support two different types.
```suggestion
CLIP models are used for text-to-image search tasks. We support two different types of CLIP models:
```

2023-04-19 12:34 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +- `clip-base-en` and `clip-large-en` are both CLIP models trained only on English text,
```suggestion
- English only models `clip-base-en` and `clip-large-en`,
```

2023-04-19 12:37 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +- `clip-base-multi` is a multilingual model that has been trained on the [laion5b](https://laion.ai/blog/laion-5b/)
```suggestion
- A multilingual model `clip-base-multi`, trained on the [laion5b](https://laion.ai/blog/laion-5b/)
```

2023-04-19 12:38 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +Similarly to the models used for text-to-text tasks, these models are transformer-based, and are loaded from the huggingface
```suggestion
Like the models used for text-to-text tasks, these models are transformer-based, and are loaded from the huggingface
```

2023-04-19 12:40 UTC, scott-martens commented on docs/walkthrough/choose-backbone.md
> +Currently, we only support one model for mesh-to-mesh search, `pointnet-base`, which we derived from the popular
```suggestion
Currently, we only support one model for mesh-to-mesh search, `pointnet-base`, which we derived from the popular 
```

2023-04-19 12:56 UTC, guenthermi requested changes
Added some comment. 
Some things which I think are missing are:
- some information about the `display_name` and the `descriptor`
- a small noticed that the names are used in the fit function, may in one of the first sentences.
- Maybe ask Bo about this, but we could also describe how to build the pre-trained models. Though, how to use them to encode something should be explained in a different section
- You can also already add descriptions for the models used in the synthesis task. We will soon add multi-lingual models for synthesis. Then this can be extended.

2023-04-19 15:05 UTC, LMMilliken commented on docs/walkthrough/choose-backbone.md
> +Currently, we only support one model for mesh-to-mesh search, `pointnet-base`, which we derived from the popular
Did you mean to suggest a change here?

2023-04-20 15:07 UTC, gmastrapas commented on docs/walkthrough/choose-backbone.md
> +Each model has its own variants and are designed to produce embeddings for a specific modality.
```suggestion
Each model has its own variants and is designed to produce embeddings for a specific modality.
```

2023-04-20 15:09 UTC, gmastrapas commented on docs/walkthrough/choose-backbone.md
> +These transformer-based models are loaded from the huggingface
```suggestion
These transformer-based models are loaded using the huggingface
```

2023-04-20 15:10 UTC, gmastrapas commented on docs/walkthrough/choose-backbone.md
> +  requires higher computational resources than resnet50.
```suggestion
  requires higher computational resources than resnet50 (base variant).
```

2023-04-20 15:11 UTC, gmastrapas commented on docs/walkthrough/choose-backbone.md
> +Like the models used for text-to-text tasks, these models are transformer-based, and are loaded from the huggingface
```suggestion
Like the models used for text-to-text tasks, these models are transformer-based, and are loaded using the huggingface
```

2023-04-20 15:13 UTC, gmastrapas commented on docs/walkthrough/choose-backbone.md
> +While each model has their own set of options, the `sbert_base_en` model, as shown in the example above, has the four most common options.
```suggestion
While each model has their own set of options, the `sbert-base-en` model, as shown in the example above, has the four most common options.
```

2023-04-20 16:17 UTC, gmastrapas approved these changes

2023-04-21 08:56 UTC, merged